# Generated by Django 3.2.12 on 2024-03-12 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={},
        ),
    ]
