# Generated by Django 3.2.12 on 2024-03-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiuser', '0002_alter_apikey_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='last_accessed_ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='api_secret',
            field=models.CharField(blank=True, editable=False, max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='app_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
