# Generated by Django 3.2.12 on 2024-03-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiuser', '0003_auto_20240312_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='api_secret',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
    ]
